In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('Iris.csv')

In [3]:
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    str
dtypes: float64(4), str(1)
memory usage: 5.9 KB

In [5]:
df.replace('?',np.nan,inplace=True)

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [6]:
df.dropna(inplace=True)

In [7]:
numeric_cols = df.select_dtypes(include=np.number).columns

df = df[(df[numeric_cols] >= 0).all(axis=1)]

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    str
dtypes: float64(4), str(1)
memory usage: 5.9 KB

In [9]:
Q1=df[numeric_cols].quantile(0.25)
Q3=df[numeric_cols].quantile(0.75)

IQR=Q3-Q1

lowerlimit=Q1-1.5*IQR
upperlimit=Q3+1.5*IQR

df=df[~((df[numeric_cols]<lowerlimit) | (df[numeric_cols]>upperlimit)).any(axis=1)]

df.shape

(145, 5)

In [10]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [11]:
scaler=StandardScaler()
X=scaler.fit_transform(x)

In [12]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
lr_model=LogisticRegression()
lr_model.fit(X_train, y_train)
lr_predict=lr_model.predict(X_test)

In [14]:
lr_accuracy=accuracy_score(y_test, lr_predict)
print("Logestic Regression accuracy : ", lr_accuracy)

Logestic Regression accuracy :  0.896551724137931

In [15]:
nb_model=GaussianNB()
nb_model.fit(X_train, y_train)
nb_predict=nb_model.predict(X_test)

In [16]:
nb_accuracy=accuracy_score(y_test, nb_predict)
print("Naive Bayes accuracy : ", nb_accuracy)

Naive Bayes accuracy :  0.9310344827586207